"""Build a large labeled set for calibration.

The starter labeled set has only a handful of negatives, so a clean false
positive rate on it means little. This script fetches the most downloaded real
packages per ecosystem and merges them, labeled good, with the hand curated
positives you already have. Calibrating against the result measures the false
positive rate on the long tail where the real false positives hide.

Sources:

  * PyPI: the maintained top packages dump (a monthly BigQuery export). It is
    a genuine download ranking, so we take the first N project names.
  * npm: npm has no official global ranking endpoint, so we gather popular
    packages through the registry popularity biased search across a spread of
    broad seed terms and dedupe. This is a popularity sample, not an exact
    ranking, which is fine for a negative set.

Standard library only, in keeping with the zero dependency rule. This is a
developer tool run by hand, not part of the shipped package.

Usage:
    python scripts/fetch_top_packages.py --count 1000
    python scripts/fetch_top_packages.py --count 300 --out data/labeled_medium.json
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path

_PYPI_TOP_URL = (
    "https://raw.githubusercontent.com/hugovk/top-pypi-packages/main/"
    "top-pypi-packages.min.json"
)
_NPM_SEARCH_URL = "https://registry.npmjs.org/-/v1/search"
_UA = "slopstop-fetcher/0.1"

# Broad seed terms used to pull popular npm packages across many domains. The
# search is biased toward popularity, so the top hits per term are real, widely
# used packages. Deduped across terms, these yield a large negative set.
_NPM_SEEDS = [
    "react", "vue", "angular", "svelte", "node", "http", "server", "cli",
    "test", "util", "data", "api", "css", "aws", "types", "eslint", "webpack",
    "babel", "logger", "json", "stream", "auth", "date", "database", "graphql",
    "router", "config", "parser", "format", "async", "crypto", "file", "image",
    "email", "queue", "cache", "socket", "template", "validation", "markdown",
]


def _get_json(url: str, timeout: int = 30) -> dict:
    req = urllib.request.Request(url, headers={"User-Agent": _UA})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


def fetch_pypi_top(count: int) -> list[str]:
    data = _get_json(_PYPI_TOP_URL)
    rows = data.get("rows") or []
    names: list[str] = []
    for row in rows:
        project = row.get("project")
        if project:
            names.append(project)
        if len(names) >= count:
            break
    return names


def fetch_npm_top(count: int) -> list[str]:
    seen: set[str] = set()
    names: list[str] = []
    for seed in _NPM_SEEDS:
        if len(names) >= count:
            break
        params = f"?text={seed}&size=100&popularity=1.0"
        try:
            data = _get_json(_NPM_SEARCH_URL + params)
        except Exception as exc:  # noqa: BLE001
            print(f"  warning: npm seed {seed!r} failed: {exc}", file=sys.stderr)
            continue
        for obj in data.get("objects", []):
            name = obj.get("package", {}).get("name")
            if name and name not in seen:
                seen.add(name)
                names.append(name)
                if len(names) >= count:
                    break
    return names


def load_existing(path: Path) -> list[dict]:
    if not path.exists():
        return []
    payload = json.loads(path.read_text(encoding="utf-8"))
    return payload.get("cases", [])


def build(count: int, labeled_path: Path, out_path: Path) -> None:
    existing = load_existing(labeled_path)
    positives = [c for c in existing if c.get("label") == "bad"]
    existing_names = {(c["ecosystem"], c["name"].lower()) for c in existing}

    print(f"keeping {len(positives)} curated positives from {labeled_path}")

    print(f"fetching top {count} pypi packages ...")
    pypi = fetch_pypi_top(count)
    print(f"  got {len(pypi)}")

    print(f"fetching up to {count} popular npm packages ...")
    npm = fetch_npm_top(count)
    print(f"  got {len(npm)}")

    cases: list[dict] = list(existing)  # preserve everything already labeled
    added = 0
    for eco, names in (("pypi", pypi), ("npm", npm)):
        for name in names:
            key = (eco, name.lower())
            if key in existing_names:
                continue
            existing_names.add(key)
            cases.append({"ecosystem": eco, "name": name, "label": "good"})
            added += 1

    goods = sum(1 for c in cases if c["label"] == "good")
    bads = sum(1 for c in cases if c["label"] == "bad")

    payload = {
        "_comment": (
            "Generated by scripts/fetch_top_packages.py. Negatives are the top "
            "downloaded real packages, labeled good. Positives are carried over "
            "from the curated labeled set. Regenerate monthly as rankings shift."
        ),
        "cases": cases,
    }
    out_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(
        f"\nwrote {out_path}: {len(cases)} cases "
        f"({goods} good, {bads} bad), {added} new negatives added"
    )
    print(
        "\nnext: slopstop calibrate "
        f"{out_path}\n"
        "note: this runs one live lookup per case, so a large set takes a few "
        "minutes. Start with a smaller --count if you want a quick pass first."
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build a large calibration set from top downloaded packages."
    )
    parser.add_argument(
        "--count", type=int, default=1000,
        help="how many top packages to fetch per ecosystem (default 1000)",
    )
    parser.add_argument(
        "--labeled", default="data/labeled_set.json",
        help="existing labeled set to carry positives from",
    )
    parser.add_argument(
        "--out", default="data/labeled_set_full.json",
        help="where to write the combined set",
    )
    args = parser.parse_args()
    build(args.count, Path(args.labeled), Path(args.out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
